variables:
  - group: AWS
  - name: cloudformation-template
    value: '$(System.DefaultWorkingDirectory)/template.yml'  

trigger:
  branches:
    include:
      - master 

resources:
  - repo: self
    clean: all
    fetchDepth: 1

stages:
  - stage: Deploy_cloudformation_template
    displayName: Pipeline
    jobs:
      - job: Linters
        displayName: Template validation
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
            displayName: 'AWS Shell Script'
            inputs:
              awsCredentials: AWS service connection
              regionName: $(region)
              scriptType: inline
              inlineScript: 'aws cloudformation validate-template --template-body "file://$(cloudformation-template)"'

      - job: Deploy
        displayName: Template deploy
        dependsOn: Linters
        condition: succeeded()
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: AmazonWebServices.aws-vsts-tools.CloudFormationCreateOrUpdateStack.CloudFormationCreateOrUpdateStack@1
            displayName: 'Create/Update Stack: $(name-stack)'
            inputs:
              awsCredentials: AWS service connection
              regionName: $(region)
              stackName: $(name-stack)
              templateSource: file
              templateFile: $(cloudformation-template)
